import { useState } from 'react'
import Head from 'next/head' 
import { RandomFox } from '@/components/RandomFox'

interface ImageItem {
  id: string,
  url: string
}

const randomNumber = (): number => Math.floor(Math.random() * 123) + 1
const generateId = (): string => Math.random().toString(36).substr(2, 9)

export default function Home() {
  // const image = `https://randomfox.ca/images/${randomNumber()}.jpg`
  const [images, setImages] = useState<ImageItem[]>([
    {id: generateId(), url: `https://randomfox.ca/images/${randomNumber()}.jpg`},
    {id: generateId(), url: `https://randomfox.ca/images/${randomNumber()}.jpg`},
    {id: generateId(), url: `https://randomfox.ca/images/${randomNumber()}.jpg`},
    {id: generateId(), url: `https://randomfox.ca/images/${randomNumber()}.jpg`},
  ])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello Platzi!
          
          {images.map((image) => (
            <div key={image.id} className='p-4'>
              <RandomFox image={image.url} alt='Fox' />
            </div>
          ))}

        </h1>
      </main>
    </>
  )
}
