import { useState } from 'react'
import Head from 'next/head' 
import { RandomFox } from '@/components/RandomFox'

// generate a random number between 1 and 123
const randomNumber = (): number => Math.floor(Math.random() * 123) + 1

export default function Home() {
  // const image = `https://randomfox.ca/images/${randomNumber()}.jpg`
  const [images, setImages] = useState<string[]>([
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
  ])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello Platzi!
          
          {images.map((image, index) => (
            <div key={index} className='p-4'>
              <RandomFox image={image} alt='Fox' />
            </div>
          ))}

        </h1>
      </main>
    </>
  )
}
